theme: jekyll-theme-minimal
title: Creative Waste
description: >
  Creative Industries Experiences (I) Project
  
  Group B

  Audrey Combe (PA6088409)
  Jakub Kubát (N76088400)
  Jan Sokol (P76088401)
  Leung Cheuk Wing (PA6088417)Jan Sokol

logo: files/logo.jpg

defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      author: "Mr. Hyde"
      category: "project"
