theme: jekyll-theme-minimal
title: Creative Waste
description: >
  Creative Cultural Experience project

  Jan Sokol

  Jakub Kubat

  Audrey Combe
  
  Tiffany Leung
logo: files/logo.jpg

defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      author: "Mr. Hyde"
      category: "project"
